app:
  name: "go-protos"
  version: "1.0.0"
  environment: "development"
  debug: true
  host: "0.0.0.0"
  port: 8080                    # HTTP端口
  read_timeout: "30s"
  write_timeout: "30s"

database:
  type: "mysql"
  host: "localhost"
  port: 3306
  username: "glauy"
  password: "123456"
  database: "testdb"
  charset: "utf8mb4"
  max_open: 50                         # 最大打开连接数
  max_idle: 10                         # 最大空闲连接数
  max_life: "30m"                      # 连接最大生存时间

grpc:
  host: "0.0.0.0"
  port: 9090                    # gRPC端口
  reflection: true
  read_timeout: "30s"
  write_timeout: "30s"

log:
  level: "info"
  format: "json"
  output: "stdout"
  filename: "app.log"
